# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubernetes:
  host: https://kubernetes.default

replicaCount: 1

helloworld:
  namespace: default
  image:
    name: tutum/hello-world
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress
